version: '3'

services:
  php-server:
    image: iserter/php-fpm:7.4 # this image is also on steroids.
    container_name: laravel_php
    depends_on:
      - mysql
      - redis
    volumes:
      - ./:/app
    networks:
      - backend
    working_dir: /app

  queue-worker:
    build: .devops/queue-worker
    image: iserter/laravel-worker
    container_name: laravel_worker
    command: php artisan horizon
    depends_on:
      - mysql
    volumes:
      - ./:/app
    networks:
      - backend
    working_dir: /app

  #  node:
#    image: node:12.16.1-alpine
#    volumes:
#      - ./:/app:cached

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app_database
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:8000"
    volumes:
      - .devops/nginx/app.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/app
    depends_on:
      - php-server
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6379:6379"
    networks:
      - backend

volumes:
  db-data:

networks:
  backend:
