# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: iserter/php-fpm:7.4
      - image: circleci/mysql:8.0
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD: 'secret'
          MYSQL_DATABASE: app_testing
      - image: redis:3
    working_directory: ~/app
    steps:
      - checkout
      - run: composer self-update

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Setup Laravel testing environment variables for CircleCI test
          command: cp .env.testing .env

      - run:
          name: Create SQLite Database
          command: touch storage/testing.sqlite

      - run:
          name: Migrate Laravel Database
          command: php artisan migrate --env=testing --force

      - run:
          name: Seed Test Data
          command: php artisan db:seed

      - run:
          name:  Run Tests
          command: ./vendor/bin/phpunit

  deploy_staging:
    docker:
      - image: circleci/php:7.2-browsers
    working_directory: ~/app
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "FINGERPRINT:HERE"
      - run:
          name: Install Deployer
          command: |
            curl -LO https://deployer.org/deployer.phar
            sudo mv deployer.phar /usr/local/bin/dep
            sudo chmod +x /usr/local/bin/dep
      - run:
          name: Deploy
          command: |
            dep deploy staging

workflows:
  version: 2
  build:
    jobs:
      - build
#      - deploy_staging:
#          requires:
#            - build
#          filters:
#            branches:
#              only: dev
